server:
  port: 8080
  address: 0.0.0.0

spring:
  data:
    mongodb:
      #uri: mongodb://localhost:27017/grocerydb #locally
      uri: mongodb://host.docker.internal:27017/grocery #proxmox
  mail:
    host: smtp.gmail.com
    port: 587
    username: abdoulaye.dllo2002@gmail.com
    password: irmiouyjvocbdcku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: grocery_secret_key_must_be_very_long_and_secure_2026

google:
  sheets:
    url: "https://script.google.com/macros/s/AKfycbzAE4pvZ1tug4JO5ANwVZAlg1EnrSqxSNPhd-1_QtnwvEkIm8ahpYKUEPf3gf9wKWGrHw/exec"
    api-key: "grocery_secret_2026"